version: 2

sources:
  - name: northwind_store
    database: northwind_store_dw_aws
    schema: raw
    tables:
      - name: customer_customer_demo
      - name: customer_demographics
      - name: employee_territories
      - name: order_details
      - name: orders
      - name: customers
      - name: products
      - name: shippers
      - name: suppliers
      - name: territories
      - name: us_states
      - name: categories
      - name: region
      - name: employees